name: exp001 # 実験名
dataset: sushi # movielens or sushi
seed: 42 # seed
num_institution: 10 # 機関数
num_institution_user: 50 # 機関ごとのユーザー数
num_anchor_data: 1000 # アンカーデータの数
dim_intermediate: 500 # 中間表現の次元数
dim_integrate: 300 # 統合表現の次元数
neighbors_centlize: 30 # 集中解析での協調フィルタリングの近傍数
neighbors_individual: 5 # 個別解析での協調フィルタリングの近傍数

